export const LOAD_MESSAGES_STATUS_LOADING = 'LOADING';
export const LOAD_MESSAGES_STATUS_SUCCEEDED = 'SUCCEEDED';
export const LOAD_MESSAGES_STATUS_FAILED = 'FAILED';
export const LOAD_MESSAGES_STATUS_IDLE = 'FAILED';

export const SESSION_STATUS_LOADING = 'LOADING';
export const SESSION_STATUS_SUCCEEDED = 'SUCCEEDED';
export const SESSION_STATUS_FAILED = 'FAILED';
export const SESSION_STATUS_IDLE = 'FAILED';

export const CREATE_SESSION_STATUS_LOADING = 'LOADING';
export const CREATE_SESSION_STATUS_SUCCEEDED = 'SUCCEEDED';
export const CREATE_SESSION_STATUS_FAILED = 'FAILED';
export const CREATE_SESSION_STATUS_IDLE = 'FAILED';

export const SEND_MESSAGE_STATUS_LOADING = 'LOADING';
export const SEND_MESSAGE_STATUS_SUCCEEDED = 'SUCCEEDED';
export const SEND_MESSAGE_STATUS_FAILED = 'FAILED';
export const SEND_MESSAGE_STATUS_IDLE = 'FAILED';