export const MESSAGE_STATUS_LOADING = 'LOADING'
export const MESSAGE_STATUS_SUCCEEDED = 'SUCCEEDED';
export const MESSAGE_STATUS_FAILED = 'FAILED';
export const MESSAGE_STATUS_IDLE = 'FAILED';

export const SESSION_STATUS_LOADING = 'LOADING'
export const SESSION_STATUS_SUCCEEDED = 'SUCCEEDED';
export const SESSION_STATUS_FAILED = 'FAILED';
export const SESSION_STATUS_IDLE = 'FAILED';

export const CREATE_STATUS_LOADING = 'LOADING'
export const CREATE_STATUS_SUCCEEDED = 'SUCCEEDED';
export const CREATE_STATUS_FAILED = 'FAILED';
export const CREATE_STATUS_IDLE = 'FAILED';

export const SEND_STATUS_LOADING = 'LOADING'
export const SEND_STATUS_SUCCEEDED = 'SUCCEEDED';
export const SEND_STATUS_FAILED = 'FAILED';
export const SEND_STATUS_IDLE = 'FAILED';