export const LOGIN_STATUS_LOADING = 'LOADING';
export const LOGIN_STATUS_SUCCEEDED = 'SUCCEEDED';
export const LOGIN_STATUS_FAILED = 'FAILED';
export const LOGIN_STATUS_IDLE = 'IDLE';

export const REGISTER_STATUS_LOADING = 'LOADING';
export const REGISTER_STATUS_SUCCEEDED = 'SUCCEEDED';
export const REGISTER_STATUS_FAILED = 'FAILED';
export const REGISTER_STATUS_IDLE = 'IDLE';