from llm.raw.utils.config import TOOL_NAME_RETRIEVE, TOOL_NAME_MULTIPLY


class WorkFlow:
    AGENT = "$AGENT"
    CALL_TOOLS = "$CALL_TOOLS"
    REWRITE = "$REWRITE"
    GENERATE = "$GENERATE"
    GRADE_DOCS = "$GRADE_DOCS"


TOOL_TO_NEXT_NODES = {
    TOOL_NAME_RETRIEVE: WorkFlow.GRADE_DOCS,
    TOOL_NAME_MULTIPLY: WorkFlow.GENERATE,
}
